plugin:
    name: 'luismayta.coordinacion::lang.plugin.name'
    description: 'luismayta.coordinacion::lang.plugin.description'
    author: 'Luis Mayta'
    icon: oc-icon-users
    homepage: ''
navigation:
    main-menu-item:
        label: 'Grupo oracion'
        url: luismayta/coordinacion/hermanoscontroller
        icon: icon-users
        sideMenu:
            side-menu-item6:
                label: Hermanos
                url: luismayta/coordinacion/hermanoscontroller
                icon: icon-users
            side-menu-item:
                label: Reuniones
                url: luismayta/coordinacion/reunionescontroller
                icon: icon-building
            side-menu-item2:
                label: Eventos
                url: luismayta/coordinacion/eventoscontroller
                icon: icon-calendar
            side-menu-item3:
                label: Tareas
                url: luismayta/coordinacion/tareascontroller
                icon: icon-tasks
            side-menu-item4:
                label: Sabados
                url: luismayta/coordinacion/sabadoscontroller
                icon: icon-home
            side-menu-item5:
                label: Aportes
                url: luismayta/coordinacion/aportescontroller
                icon: icon-dollar
            side-menu-item7:
                label: Asistencias
                url: luismayta/coordinacion/asistenciascontroller
                icon: icon-adn
            side-menu-item8:
                label: Servicios
                url: luismayta/coordinacion/servicioscontroller
                icon: icon-sitemap
            side-menu-item9:
                label: Actas
                url: luismayta/coordinacion/actascontroller
                icon: icon-book
