list: $/luismayta/coordinacion/models/actas/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Actas
title: ActasController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/actascontroller/update/:id'
