list: $/luismayta/coordinacion/models/grupooracion/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\GrupoOracion
title: GrupoOracionController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/grupooracioncontroller/update/:id'
