list: $/luismayta/coordinacion/models/asistencias/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Asistencias
title: AsistenciasController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/asistenciascontroller/update/:id'
