list: $/luismayta/coordinacion/models/tareas/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Tareas
title: TareasController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/tareascontroller/update/:id'
