list: $/luismayta/coordinacion/models/mensajes/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Mensajes
title: MensajesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/mensajescontroller/update/:id'
