list: $/luismayta/coordinacion/models/reuniones/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Reuniones
title: ReunionesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/reunionescontroller/update/:id'
