list: $/luismayta/coordinacion/models/eventos/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Eventos
title: EventosController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/eventoscontroller/update/:id'
