list: $/luismayta/coordinacion/models/sabado/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Sabado
title: SabadosController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/sabadoscontroller/update/:id'
