list: $/luismayta/coordinacion/models/servicios/columns.yaml
modelClass: LuisMayta\Coordinacion\Models\Servicios
title: ServiciosController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/coordinacion/servicioscontroller/update/:id'
